feat: jpyx-2 update add node
lcnem/jpyx pull request #11
Opened 2021-08-03 07:29 UTC by Senna46

jpyx-2 アップデートのためのファイル作成

①シェルスクリプトファイル作成
 全ノードのgentxコマンドを記述

②genesis-pretty.json
 新ノードのアドレスをVestingAccountとしてgenesis.jsonのaccounts配列に追加
 balances配列にその鍵のアドレスと残高1バリデータ分（5000000000）を足す
genesisのbalances配列にて「その他のバリデータ」分から残高1バリデータ分を引く
残高425000000000

@KimuraYu45z  レビューお願いします。
もし変更点間違っていればご指摘お願いします。

2021-08-03 07:37 UTC, KimuraYu45z requested changes

2021-08-03 07:37 UTC, KimuraYu45z commented on launch/jpyx-2/genesis-pretty.json
> +  "genesis_time": "2021-04-28T11:57:54.135080089Z",
これ、7月下旬に変えてもらえると嬉しいです

2021-08-03 07:37 UTC, KimuraYu45z commented on launch/jpyx-2/genesis-pretty.json
> +          "start_time": "1619611074"
starttimeをブロックのジェネシスタイムをunix時間に変換したもの（unix時間変換ツールはネットにある）にしてもらいたいです。`"start_time": "(.+)"`みたいな感じで正規表現検索をctrl Fでかければ一気に置換できるかと。

2021-08-03 07:37 UTC, KimuraYu45z commented on launch/jpyx-2/genesis-pretty.json
> +            "end_time": "1651147074"
endtimeは既存バリデータはそのままでいいです

新バリデータだけ丸一年後をend timeにしてください

2021-08-03 07:37 UTC, KimuraYu45z commented on launch/jpyx-2/gentx-jpyx-2.sh
> +
`rm -r ~/.jpyx/config/gentx`入れとかなくていいですか？

2021-08-03 07:57 UTC, Senna46 commented
ジェネシスタイムの変更、新バリデータのエンドタイムの変更、kava-teamの削除を行っています。残高も変更できているかと思います。

2021-08-04 07:30 UTC, Senna46 commented
バリデーター報酬を集計したものをpushしてます。
![reward-list](https://user-images.githubusercontent.com/29295263/128140173-ec97f346-80da-4dd4-89cb-790db93ab130.PNG)

2021-08-04 07:59 UTC, Senna46 commented
JPYX-1の報酬分はbalanceで有効な桁数が不明なので、念の為整数に直しました。（おそらく10^(-18)まで認識しそうですが、、）

@KimuraYu45z 私の認識ではあと、new validatorのgentxを作成するだけですが、その他にありますでしょうか？

2021-08-04 08:01 UTC, KimuraYu45z commented
整数でokです。いえおっしゃる通りあとはgentxをやるだけだとおもいます。

2021-08-04 08:13 UTC, Senna46 commented
iijima-sanのgentxを作成。これですべてのファイルが揃ったかと思います。

2021-08-05 05:20 UTC, Senna46 commented
`inflation_max`これを今までのインフレ率 0.13にしてあります。
`inflation_min`もしバリデータ1のときの値。 0.0013でも良いのですが、それだとバリデータが増えても減ってもRewardが変わらず、それは不自然な気もするので0.01にしています。

`inflation_rate_change`0.12 `inflation_max-inflation_min`

現状はバリデーターが15なので、`inflation_min`+`inflation_rate_change`*(15-1)/(100-1)≒0.027
`inflation`現在のインフレ率は2.7%としました。これは今までの報酬からすると約20%に相当します。

2021-08-05 05:28 UTC, KimuraYu45z commented on launch/jpyx-2/reward-jpyx-1.csv
> +tokyo-4,2180628510
このファイルは消していいです！

2021-08-05 05:32 UTC, Senna46 commented on launch/jpyx-2/reward-jpyx-1.csv
> +tokyo-4,2180628510
もう一つRewardのメモがあったのでそれも含めて削除しました。
これでマージして良いでしょうか？

2021-08-05 05:32 UTC, KimuraYu45z approved these changes
LGTM!

2021-08-05 05:34 UTC, merged