test: change from usdx to jsmn
lcnem/jpyx pull request #66
Opened 2021-09-01 09:47 UTC by Tomosuke0930

@KimuraYu45z 
@Senna46 
@YasunoriMATSUOKA 
レビューお願いします

2021-09-01 09:49 UTC, KimuraYu45z requested changes

2021-09-01 09:49 UTC, KimuraYu45z commented on x/cdp/keeper/auctions_test.go
> +	authGS := app.NewAuthGenState([]sdk.AccAddress{taddr}, []sdk.Coins{cs(c("jsmn", 21000000000))})
これはちがいます
usdx:jpyx
kava:jsmn
の対応関係

2021-09-01 09:52 UTC, KimuraYu45z commented
コンフリクト治したので、pullお願いします

2021-09-01 09:57 UTC, Tomosuke0930 commented
承知しました！

2021-09-01 10:00 UTC, Tomosuke0930 commented
@KimuraYu45z 
こちらはpullしたら教えていただいた対応するものに変更してからpushするという認識でよろしいでしょうか？

2021-09-01 10:01 UTC, KimuraYu45z commented
そうです

2021-09-02 10:18 UTC, KimuraYu45z commented
mainからやったほうが安全

2021-09-02 10:18 UTC, closed without merging